[package]
name = "giftorio_wasm"
description = "A Factorio blueprint generator for GIF (or WebP) images."
authors = ["Colin R. King <colin.r.king@gmail.com>", "crkit"]
version = "0.2.0"
edition = "2018"
repository = "https://github.com/colinchilds/giftorio"
license = "Apache-2.0"
keywords = ["factorio", "blueprint", "gif", "webp", "image"]
categories = ["multimedia::images", "multimedia::encoding"]

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.13"
console_error_panic_hook = "0.1"
flate2 = { version = "1.0.17", features = [
    "zlib-rs",
], default-features = false }
glam = { version = "0.33.8", features = ["serde"] }
image = "0.24"
js-sys = "0.3.77"
paste = "1.0"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3", features = [
    "console",
    "Performance",
    "WorkerGlobalScope",
] }
